// Custom Jest matchers extension
// This file extends the Jest expect interface with custom matchers

// Extend Jest with custom matchers
declare namespace jest {
  interface Matchers<R> {
    /**
     * Custom matcher to check if a number is close to another number within a tolerance
     */
    toBeCloseTo(expected: number, tolerance: number): R;
    
    /**
     * Custom matcher to check if a string contains only alphabetic characters
     */
    toBeAlphabetic(): R;
    
    /**
     * Custom matcher to check if an object has all required properties
     */
    toHaveAllProperties(properties: string[]): R;
    
    /**
     * Custom matcher to check if a number is within a specified range (inclusive)
     */
    toBeInRange(min: number, max: number): R;
  }

  interface Expect {
    /**
     * Custom asymmetric matcher for numbers within a range (auto-generated by expect.extend)
     */
    toBeInRange(min: number, max: number): any;
    
    // Note: stringMatching and objectContaining are built-in Jest asymmetric matchers
    // so they don't need to be declared here
  }
}
